-- AlterTable
ALTER TABLE "Blog" ALTER COLUMN "isDeleted" DROP NOT NULL,
ALTER COLUMN "createdAt" DROP NOT NULL,
ALTER COLUMN "updatedAt" DROP NOT NULL,
ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "version" DROP NOT NULL;
